---
title: "Notes"
subtitle: "Spring 2026"
format: 
  html:
    page-layout: full
    theme: cosmo
    toc: true
    toc-title: "Contents"
    embed-resources: true
    standalone: true
editor: 
  markdown: 
    wrap: 72
---

All slides and handouts for this course can be accessed in [Google
Drive](https://drive.google.com/drive/folders/15st3JYukRb-Jn4CPmt7-ZV2dXwoqN_7x?usp=sharing).
Please note that you must have a Vassar email in order to access the
folder.

**Thur Jan 22.** 0-welcome. These slides give an overview of the course, and a brief history of LLMs.

**Tue Jan 27.** 1-R-vs-Python. These slides compare and contrast R and Python and includes a few coding exercises.

**Thu Jan 29.** Lab 1. Introduction to Git.

**Tue Feb 3.** 3-R-Python-datasci. These slides compare and contrast R and Python for manipulating datasets and includes a few coding exercises.

**Thu Feb 5.** Lab 2. R, Python, and Git, Oh My!

**Tue Feb 10.** 5-datavis-R. These slides provide examples on how to create data visualizations in R. We then created a class-info dataset and created data visualizations from it.

**Thu Feb 12.** 6-datavis-py. These slides provide examples on how to create data visualizations in Python. We went through an example with the class-info dataset, and then spent the last 30 minutes of class taking Quiz 1.

**Tue Feb 17.** 7-webscraping-R. These slides provide examples on how to use R and a CSS Selector Gadget for webs scraping. 

**Thu Feb 19.** 8-webscraping-R-py. These slides discuss how to web scrape at scale in R, and examples for web scraping in Python.

**Tue Feb 24.** 9-intro-ML. These slides introduce the big themes in machine learning and we saw examples of applying linear models, clustering analysis, and fitting a neural network to the Palmer Penguins dataset.

**Thu Feb 26.** 10-eval-models. These slides discuss training data vs. testing data, flexible models vs. rigid models, MSE, bias, and variance.

**Tue Mar 3.** 11-eval-models2. These notes discuss cross validation, bootstrapping, and linear regression.

**Thu Mar 5.** We had article discussions about machine learning and LLMs.

**Tue Mar 24.** 13-lasso-ridge. These slides discuss regularization and shrinkage methods including lasso, ridge, and elastic net. They also discuss how to implement these methods in Python.

**Thu Mar 26.** Project brainstorming day.

**Tue Mar 31.** 14-clustering-PCA. These slides and notes discuss principal component analysis (PCA) and hierarchical clustering.

**Thu Apr 2.** 15-clustering-(kernel)PCA. These slides discuss PCA, kernel PCA, hierarchical clustering, and how to implement these methods in Python.

**Tue Apr 7.** Guest speaker and project proposals.

**Thu Apr 9.** Project proposal presentations and Quiz 3.

**Tue Apr 14.** 16-deep-learning. These notes discuss the basic architecture of a neural network model, how we fit them, and some toy examples.

**Thu Apr 16.** 17-neural-nets. These slides discuss how to implement neural networks via PyTorch.

**Tue Apr 21.** Peer review project work day.

**Thu Apr 23.** We learned how to build a website through Quarto and GitHub pages and then took Quiz 4.

**Tue Apr 28.** Professor An and Professor DeFord talked about their statistical and data science research.

**Thu Apr 30.** Project Presentations.

**Tue May 5.** Project presentations and last day of class!

